import mongoose, { Schema, Document } from 'mongoose';

export enum PermissionAction {
  GET = 'get',
  POST = 'post',
  PUT = 'put',
  DELETE = 'delete',
  VIEW = 'view'
}

export interface IPermission {
  resource: string;
  action: PermissionAction;
  description?: string;
  isAutoGenerated: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface IPermissionDocument extends IPermission, Document {}

const PermissionSchema = new Schema<IPermissionDocument>(
  {
    resource: { type: String, required: true, trim: true },
    action: { 
      type: String, 
      enum: Object.values(PermissionAction), 
      required: true,
      uppercase: true 
    },
    description: { type: String, trim: true },
    isAutoGenerated: { type: Boolean, default: false }
  },
  {
    timestamps: true
  }
);

PermissionSchema.index({ resource: 1, action: 1 }, { unique: true });

export const Permission = mongoose.model<IPermissionDocument>('Permission', PermissionSchema);