export interface Role {
  _id: string;
  name: string;
  permissions: Permission[];
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Permission {
  _id: string;
  resource: string;
  action: PermissionAction;
  description?: string;
  isAutoGenerated: boolean;
}

export type PermissionAction = 'get' | 'post' | 'put' | 'delete' | 'view';

export interface CreateRoleDto {
  name: string;
  description?: string;
  permissionIds: string[];
}

export interface UpdateRoleDto extends Partial<CreateRoleDto> {}