/**
 * Servicio de permisos
 * Gestiona el CRUD de permisos en la base de datos
 */
import { Permission, PermissionAction, IPermissionDocument } from '../models/permission.model';
import { logger } from '../utils/logger';

export interface CreatePermissionDto {
  resource: string;
  action: PermissionAction;
  description?: string;
}

export interface UpdatePermissionDto {
  resource?: string;
  action?: PermissionAction;
  description?: string;
}

class PermissionService {
  async create(createPermissionDto: CreatePermissionDto): Promise<IPermissionDocument> {
    try {
      const permission = await Permission.create(createPermissionDto);
      logger.info(`Permiso creado: ${createPermissionDto.resource} - ${createPermissionDto.action}`);
      return permission;
    } catch (error: unknown) {
      if (error instanceof Error && error.message.includes('duplicate')) {
        throw new Error('El permiso ya existe');
      }
      logger.error('Error al crear permiso:', error);
      throw error;
    }
  }

  async findAll(): Promise<IPermissionDocument[]> {
    try {
      return await Permission.find().sort({ resource: 1 });
    } catch (error) {
      logger.error('Error al obtener permisos:', error);
      throw error;
    }
  }

  async findById(id: string): Promise<IPermissionDocument> {
    try {
      const permission = await Permission.findById(id);
      if (!permission) {
        throw new Error('Permiso no encontrado');
      }
      return permission;
    } catch (error) {
      logger.error('Error al obtener permiso:', error);
      throw error;
    }
  }

  async update(id: string, updatePermissionDto: UpdatePermissionDto): Promise<IPermissionDocument> {
    try {
      const permission = await Permission.findByIdAndUpdate(id, updatePermissionDto, {
        new: true,
        runValidators: true
      });
      if (!permission) {
        throw new Error('Permiso no encontrado');
      }
      logger.info(`Permiso actualizado: ${id}`);
      return permission;
    } catch (error) {
      logger.error('Error al actualizar permiso:', error);
      throw error;
    }
  }

  async delete(id: string): Promise<void> {
    try {
      const permission = await Permission.findByIdAndDelete(id);
      if (!permission) {
        throw new Error('Permiso no encontrado');
      }
      logger.info(`Permiso eliminado: ${id}`);
    } catch (error) {
      logger.error('Error al eliminar permiso:', error);
      throw error;
    }
  }

  async findByResource(resource: string): Promise<IPermissionDocument[]> {
    try {
      return await Permission.find({ resource: { $regex: resource, $options: 'i' } });
    } catch (error) {
      logger.error('Error al buscar permisos por recurso:', error);
      throw error;
    }
  }

  async upsertAutoGenerated(
    resource: string,
    action: PermissionAction,
    description?: string
  ): Promise<IPermissionDocument> {
    try {
      const permission = await Permission.findOneAndUpdate(
        { resource, action },
        { resource, action, description, isAutoGenerated: true },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
      return permission;
    } catch (error) {
      logger.error('Error al upsertar permiso autogenerado:', error);
      throw error;
    }
  }

  async findAutoGenerated(): Promise<IPermissionDocument[]> {
    try {
      return await Permission.find({ isAutoGenerated: true });
    } catch (error) {
      logger.error('Error al obtener permisos autogenerados:', error);
      throw error;
    }
  }

  async deleteAutoGenerated(): Promise<void> {
    try {
      await Permission.deleteMany({ isAutoGenerated: true });
      logger.info('Permisos autogenerados eliminados');
    } catch (error) {
      logger.error('Error al eliminar permisos autogenerados:', error);
      throw error;
    }
  }
}

export const permissionService = new PermissionService();