/**
 * Controlador de permisos
 * Gestiona las operaciones CRUD de permisos
 */
import { Response } from 'express';
import { permissionService } from '../services/permission.service';
import { ApiResponse } from '../types/api-response';
import { AuthenticatedRequest } from '../middleware/auth.middleware';
import { PermissionAction } from '../models/permission.model';

export class PermissionController {
  async getPermissions(_req: AuthenticatedRequest, res: Response<ApiResponse<any[]>>): Promise<void> {
    try {
      const permissions = await permissionService.findAll();
      res.status(200).json({ success: true, data: permissions });
    } catch (error: any) {
      res.status(500).json({ success: false, message: error.message });
    }
  }

  async getAutoGenerated(_req: AuthenticatedRequest, res: Response<ApiResponse<any[]>>): Promise<void> {
    try {
      const permissions = await permissionService.findAutoGenerated();
      res.status(200).json({ success: true, data: permissions });
    } catch (error: any) {
      res.status(500).json({ success: false, message: error.message });
    }
  }

  async getPermissionById(req: AuthenticatedRequest, res: Response<ApiResponse<any>>): Promise<void> {
    try {
      const permission = await permissionService.findById(req.params.id);
      res.status(200).json({ success: true, data: permission });
    } catch (error: any) {
      const status = error.message === 'Permiso no encontrado' ? 404 : 500;
      res.status(status).json({ success: false, message: error.message });
    }
  }

  async createPermission(req: AuthenticatedRequest, res: Response<ApiResponse<any>>): Promise<void> {
    try {
      const { resource, action, description } = req.body;

      if (!resource || !action) {
        res.status(400).json({
          success: false,
          message: 'Los campos resource y action son requeridos'
        });
        return;
      }

      if (!Object.values(PermissionAction).includes(action)) {
        res.status(400).json({
          success: false,
          message: 'Acción inválida. Debe ser: get, post, put, delete, view'
        });
        return;
      }

      const permission = await permissionService.create({ resource, action, description });
      res.status(201).json({ success: true, data: permission, message: 'Permiso creado correctamente' });
    } catch (error: any) {
      res.status(400).json({ success: false, message: error.message });
    }
  }

  async updatePermission(req: AuthenticatedRequest, res: Response<ApiResponse<any>>): Promise<void> {
    try {
      const { resource, action, description } = req.body;

      if (action && !Object.values(PermissionAction).includes(action)) {
        res.status(400).json({
          success: false,
          message: 'Acción inválida. Debe ser: get, post, put, delete, view'
        });
        return;
      }

      const permission = await permissionService.update(req.params.id, { resource, action, description });
      res.status(200).json({ success: true, data: permission, message: 'Permiso actualizado correctamente' });
    } catch (error: any) {
      const status = error.message === 'Permiso no encontrado' ? 404 : 500;
      res.status(status).json({ success: false, message: error.message });
    }
  }

  async deletePermission(req: AuthenticatedRequest, res: Response<ApiResponse<any>>): Promise<void> {
    try {
      const permission = await permissionService.findById(req.params.id);
      if (permission.isAutoGenerated) {
        res.status(403).json({
          success: false,
          message: 'No se pueden eliminar permisos autogenerados'
        });
        return;
      }
      await permissionService.delete(req.params.id);
      res.status(200).json({ success: true, message: 'Permiso eliminado correctamente' });
    } catch (error: any) {
      const status = error.message === 'Permiso no encontrado' ? 404 : 500;
      res.status(status).json({ success: false, message: error.message });
    }
  }
}

export const permissionController = new PermissionController();