/**
 * Controlador de permisos
 * Gestiona las operaciones CRUD de permisos
 */
import { Response } from 'express';
import { permissionService } from '../services/permission.service';
import { ApiResponse } from '../types/api-response';
import { AuthenticatedRequest } from '../middleware/auth.middleware';
import { PermissionAction, IPermissionDocument } from '../models/permission.model';

interface PermissionResponse {
  _id: string;
  resource: string;
  action: PermissionAction;
  description?: string;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export class PermissionController {
  async getPermissions(_req: AuthenticatedRequest, res: Response<ApiResponse<PermissionResponse[]>>): Promise<void> {
    try {
      const permissions = await permissionService.findAll() as IPermissionDocument[];
      const response: PermissionResponse[] = permissions.map(perm => ({
        _id: perm._id.toString(),
        resource: perm.resource,
        action: perm.action,
        description: perm.description,
        isAutoGenerated: perm.isAutoGenerated,
        createdAt: perm.createdAt,
        updatedAt: perm.updatedAt
      }));
      res.status(200).json({ success: true, data: response });
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Error al obtener permisos';
      res.status(500).json({ success: false, message });
    }
  }

  async getAutoGenerated(_req: AuthenticatedRequest, res: Response<ApiResponse<PermissionResponse[]>>): Promise<void> {
    try {
      const permissions = await permissionService.findAutoGenerated() as IPermissionDocument[];
      const response: PermissionResponse[] = permissions.map(perm => ({
        _id: perm._id.toString(),
        resource: perm.resource,
        action: perm.action,
        description: perm.description,
        isAutoGenerated: perm.isAutoGenerated,
        createdAt: perm.createdAt,
        updatedAt: perm.updatedAt
      }));
      res.status(200).json({ success: true, data: response });
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Error al obtener permisos autogenerados';
      res.status(500).json({ success: false, message });
    }
  }

  async getPermissionById(req: AuthenticatedRequest, res: Response<ApiResponse<PermissionResponse>>): Promise<void> {
    try {
      const permission = await permissionService.findById(req.params.id) as IPermissionDocument;
      const response: PermissionResponse = {
        _id: permission._id.toString(),
        resource: permission.resource,
        action: permission.action,
        description: permission.description,
        isAutoGenerated: permission.isAutoGenerated,
        createdAt: permission.createdAt,
        updatedAt: permission.updatedAt
      };
      res.status(200).json({ success: true, data: response });
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Error al obtener permiso';
      const status = message === 'Permiso no encontrado' ? 404 : 500;
      res.status(status).json({ success: false, message });
    }
  }

  async createPermission(req: AuthenticatedRequest, res: Response<ApiResponse<PermissionResponse>>): Promise<void> {
    try {
      const { resource, action, description } = req.body;

      if (!resource || !action) {
        res.status(400).json({
          success: false,
          message: 'Los campos resource y action son requeridos'
        });
        return;
      }

      if (!Object.values(PermissionAction).includes(action)) {
        res.status(400).json({
          success: false,
          message: 'Acción inválida. Debe ser: get, post, put, delete, view'
        });
        return;
      }

      const permission = await permissionService.create({ resource, action, description }) as IPermissionDocument;
      const response: PermissionResponse = {
        _id: permission._id.toString(),
        resource: permission.resource,
        action: permission.action,
        description: permission.description,
        isAutoGenerated: permission.isAutoGenerated,
        createdAt: permission.createdAt,
        updatedAt: permission.updatedAt
      };
      res.status(201).json({ success: true, data: response, message: 'Permiso creado correctamente' });
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Error al crear permiso';
      res.status(400).json({ success: false, message });
    }
  }

  async updatePermission(req: AuthenticatedRequest, res: Response<ApiResponse<PermissionResponse>>): Promise<void> {
    try {
      const { resource, action, description } = req.body;

      if (action && !Object.values(PermissionAction).includes(action)) {
        res.status(400).json({
          success: false,
          message: 'Acción inválida. Debe ser: get, post, put, delete, view'
        });
        return;
      }

      const permission = await permissionService.update(req.params.id, { resource, action, description }) as IPermissionDocument;
      const response: PermissionResponse = {
        _id: permission._id.toString(),
        resource: permission.resource,
        action: permission.action,
        description: permission.description,
        isAutoGenerated: permission.isAutoGenerated,
        createdAt: permission.createdAt,
        updatedAt: permission.updatedAt
      };
      res.status(200).json({ success: true, data: response, message: 'Permiso actualizado correctamente' });
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Error al actualizar permiso';
      const status = message === 'Permiso no encontrado' ? 404 : 500;
      res.status(status).json({ success: false, message });
    }
  }

  async deletePermission(req: AuthenticatedRequest, res: Response<ApiResponse<boolean>>): Promise<void> {
    try {
      const permission = await permissionService.findById(req.params.id) as IPermissionDocument;
      if (permission.isAutoGenerated) {
        res.status(403).json({
          success: false,
          message: 'No se pueden eliminar permisos autogenerados'
        });
        return;
      }
      await permissionService.delete(req.params.id);
      res.status(200).json({ success: true, data: true, message: 'Permiso eliminado correctamente' });
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Error al eliminar permiso';
      const status = message === 'Permiso no encontrado' ? 404 : 500;
      res.status(status).json({ success: false, message });
    }
  }
}

export const permissionController = new PermissionController();