/**
 * Rutas de permisos
 * Endpoints para gestión de permisos (protegidos por middleware de permisos)
 */
import { Router } from 'express';
import { permissionController } from '../controllers/permission.controller';
import { checkPermission } from '../middleware/permisos.middleware';
import { authMiddleware, AuthenticatedRequest } from '../middleware/auth.middleware';

const router = Router();

router.use(authMiddleware);
router.use(checkPermission);

router.get('/', (req, res, next) => permissionController.getPermissions(req as AuthenticatedRequest, res, next));
router.get('/auto-generated', (req, res, next) => permissionController.getAutoGenerated(req as AuthenticatedRequest, res, next));
router.get('/:id', (req, res, next) => permissionController.getPermissionById(req as AuthenticatedRequest, res, next));
router.post('/', (req, res, next) => permissionController.createPermission(req as AuthenticatedRequest, res, next));
router.put('/:id', (req, res, next) => permissionController.updatePermission(req as AuthenticatedRequest, res, next));
router.delete('/:id', (req, res, next) => permissionController.deletePermission(req as AuthenticatedRequest, res, next));

export default router;