/**
 * Rutas de permisos
 * Endpoints para gestión de permisos (protegidos por middleware de permisos)
 */
import { Router, Response } from 'express';
import { permissionService } from '../services/permission.service';
import { checkPermission } from '../middleware/permisos.middleware';
import { authMiddleware, AuthenticatedRequest } from '../middleware/auth.middleware';
import { ApiResponse } from '../types/api-response';
import { PermissionAction } from '../models/permission.model';

const router = Router();

router.use(authMiddleware);
router.use(checkPermission);

router.get('/', async (req: AuthenticatedRequest, res: Response<ApiResponse<any[]>>) => {
  try {
    const permissions = await permissionService.findAll();
    res.status(200).json({ success: true, data: permissions });
  } catch (error: any) {
    res.status(400).json({ success: false, message: error.message });
  }
});

router.get('/auto-generated', async (req: AuthenticatedRequest, res: Response<ApiResponse<any[]>>) => {
  try {
    const permissions = await permissionService.findAutoGenerated();
    res.status(200).json({ success: true, data: permissions });
  } catch (error: any) {
    res.status(400).json({ success: false, message: error.message });
  }
});

router.get('/:id', async (req: AuthenticatedRequest, res: Response<ApiResponse<any>>) => {
  try {
    const permission = await permissionService.findById(req.params.id);
    res.status(200).json({ success: true, data: permission });
  } catch (error: any) {
    res.status(400).json({ success: false, message: error.message });
  }
});

router.post('/', async (req: AuthenticatedRequest, res: Response<ApiResponse<any>>) => {
  try {
    const { resource, action, description } = req.body;
    
    if (!resource || !action) {
      res.status(400).json({ 
        success: false, 
        message: 'Los campos resource y action son requeridos' 
      });
      return;
    }

    if (!Object.values(PermissionAction).includes(action)) {
      res.status(400).json({ 
        success: false, 
        message: 'Acción inválida. Debe ser: get, post, put, delete, view' 
      });
      return;
    }

    const permission = await permissionService.create({ resource, action, description });
    res.status(201).json({ success: true, data: permission, message: 'Permiso creado correctamente' });
  } catch (error: any) {
    res.status(400).json({ success: false, message: error.message });
  }
});

router.put('/:id', async (req: AuthenticatedRequest, res: Response<ApiResponse<any>>) => {
  try {
    const { resource, action, description } = req.body;
    
    if (action && !Object.values(PermissionAction).includes(action)) {
      res.status(400).json({ 
        success: false, 
        message: 'Acción inválida. Debe ser: get, post, put, delete, view' 
      });
      return;
    }

    const permission = await permissionService.update(req.params.id, { resource, action, description });
    res.status(200).json({ success: true, data: permission, message: 'Permiso actualizado correctamente' });
  } catch (error: any) {
    res.status(400).json({ success: false, message: error.message });
  }
});

router.delete('/:id', async (req: AuthenticatedRequest, res: Response<ApiResponse<any>>) => {
  try {
    await permissionService.delete(req.params.id);
    res.status(200).json({ success: true, message: 'Permiso eliminado correctamente' });
  } catch (error: any) {
    res.status(400).json({ success: false, message: error.message });
  }
});

export default router;