/**
 * Utilidad para escanear endpoints registrados en Express
 * Guarda automáticamente los endpoints en la colección Permission de MongoDB
 */
import { Application } from 'express';
import { permissionService } from '../services/permission.service';
import { PermissionAction, IPermissionDocument } from '../models/permission.model';
import { logger } from '../utils/logger';

interface RouteInfo {
  path: string;
  method: string;
}

interface LayerRoute {
  route?: {
    path: string;
    methods: Record<string, boolean>;
  };
  regexp?: RegExp;
  handle?: {
    stack?: LayerRoute[];
  };
}

const httpMethodToAction: Record<string, PermissionAction> = {
  GET: PermissionAction.GET,
  POST: PermissionAction.POST,
  PUT: PermissionAction.PUT,
  DELETE: PermissionAction.DELETE,
  PATCH: PermissionAction.PUT
};

export const scanRoutes = (app: Application): RouteInfo[] => {
  const routes: RouteInfo[] = [];
  const processedPaths = new Set<string>();

  const stack = app._router?.stack || [];

  for (const layer of stack) {
    if (layer.route) {
      const route = layer.route;
      const method = Object.keys(route.methods)[0]?.toUpperCase() || 'GET';
      const path = route.path;
      const key = `${method}:${path}`;

      if (!processedPaths.has(key)) {
        routes.push({ path, method });
        processedPaths.add(key);
      }
    } else if (layer.handle?.stack) {
      const processLayer = (lr: LayerRoute, basePath: string = '') => {
        if (lr.route) {
          const route = lr.route;
          const method = Object.keys(route.methods)[0]?.toUpperCase() || 'GET';
          const path = basePath + route.path;
          const key = `${method}:${path}`;

          if (!processedPaths.has(key)) {
            routes.push({ path, method });
            processedPaths.add(key);
          }
        }

        if (lr.handle?.stack) {
          for (const child of lr.handle.stack) {
            const regexpSource = lr.regexp ? lr.regexp.source.replace(/\\\//g, '/').replace(/[\^$]/g, '').replace(/\(\?:.*?\)/g, '').replace(/\|/g, '/') : '';
            processLayer(child, basePath + regexpSource);
          }
        }
      };

      processLayer(layer);
    }
  }

  return routes;
};

export const generatePermissionsFromRoutes = async (app: Application): Promise<void> => {
  try {
    logger.info('Iniciando escaneo de rutas...');

    await permissionService.deleteAutoGenerated();

    const routes = scanRoutes(app);
    logger.info(`Se encontraron ${routes.length} rutas`);

    const generatedPermissions: IPermissionDocument[] = [];

    for (const route of routes) {
      if (route.path.startsWith('/api/') && !route.path.includes('health')) {
        const action = httpMethodToAction[route.method] || PermissionAction.GET;

        try {
          const permission = await permissionService.upsertAutoGenerated(
            route.path,
            action,
            `Permiso autogenerado para ${route.method} ${route.path}`
          );
          generatedPermissions.push(permission);
        } catch (error: unknown) {
          const message = error instanceof Error ? error.message : 'Error desconocido';
          logger.warn(`Error al generar permiso para ${route.path}: ${message}`);
        }
      }
    }

    logger.info(`Se generaron ${generatedPermissions.length} permisos automáticamente`);
  } catch (error) {
    logger.error('Error al generar permisos desde rutas:', error);
    throw error;
  }
};